# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3ab2f5fdffb15a46901c6b581afdcc6918228143c7f4d7cf01f037225f4806874856ca7739229ef2798c41738e4173ac35c14a22ddc176e9c900b6aeda5c366

test:
  secret_key_base: 14d09cecce1f5c0da35cfc1d4822fa55d497fc9a27c91f1744638627d5fccd7d137082ad5fc5c0f14421a31359be148163b5b9e7f9ad1e1918814864ef6395d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
